version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoge-db
      MYSQL_USER: user
      MYSQL_PASSWORD: p@ssw0rd
      TZ: Asia/Tokyo
    ports:
        - 3001:3306
    volumes:
        - db-store:/var/lib/mysql
        - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store: